---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:etcd
rules:
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - "certificatesigningrequests"
  - "certificatesigningrequests/approval"
  - "certificatesigningrequests/status"
  verbs:
  - update
  - create
  - get
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: system:etcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:etcd
subjects:
- kind: ServiceAccount
  name: etcd
  namespace: default
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: etcd
  namespace: default
spec:
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  replicas: 3
  template:
    metadata:
      labels:
        app: etcd
    spec:
      serviceAccount: etcd
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: kube-csr
        image: quay.io/julienbalestra/kube-csr:latest
        command:
        - /usr/local/bin/kube-csr
        - issue
        - $(MY_POD_NAME)
        - --csr-name=$(MY_POD_NAME)-$(MY_POD_UID)
        - --generate
        - --submit
        - --approve
        - --fetch
        - --subject-alternative-names=$(MY_POD_IP),$(MY_POD_NAME).etcd.$(MY_POD_NAMESPACE).svc.cluster.local,etcd.$(MY_POD_NAMESPACE).svc.cluster.local
        - --private-key-file=/etc/certs/etcd.private_key
        - --csr-file=/etc/certs/etcd.csr
        - --certificate-file=/etc/certs/etcd.certificate
        env:
        - name: MY_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: certs
          mountPath: /etc/certs

      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        command:
        - /usr/local/bin/etcd

        - --cert-file=/etc/certs/etcd.certificate
        - --key-file=/etc/certs/etcd.private_key
        - --trusted-ca-file=/run/secrets/kubernetes.io/serviceaccount/ca.crt

        - --advertise-client-urls=https://$(MY_POD_NAME).etcd.$(MY_POD_NAMESPACE).svc.cluster.local:2379
        - --listen-client-urls=https://$(MY_POD_IP):2379,http://127.0.0.1:2379
        # TODO use --client-cert-auth

        - --peer-cert-file=/etc/certs/etcd.certificate
        - --peer-key-file=/etc/certs/etcd.private_key
        - --peer-ca-file=/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --name=$(MY_POD_NAME)
        - --listen-peer-urls=https://0.0.0.0:2380
        - --initial-advertise-peer-urls=https://$(MY_POD_NAME).etcd.$(MY_POD_NAMESPACE).svc.cluster.local:2380
        - --initial-cluster
        - etcd-0=https://etcd-0.etcd.$(MY_POD_NAMESPACE).svc.cluster.local:2380,etcd-1=https://etcd-1.etcd.$(MY_POD_NAMESPACE).svc.cluster.local:2380,etcd-2=https://etcd-2.etcd.$(MY_POD_NAMESPACE).svc.cluster.local:2380
        - --peer-client-cert-auth
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 2379
          name: etcd
        volumeMounts:
        - name: certs
          mountPath: /etc/certs
        livenessProbe:
          tcpSocket:
            port: etcd
          initialDelaySeconds: 60
          periodSeconds: 5
      volumes:
      - emptyDir:
        name: certs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: etcdctl
  namespace: default
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 60
  template:
    metadata:
      labels:
        app: etcdctl
    spec:
      containers:
      - name: etcdctl
        image: quay.io/coreos/etcd:latest
        command:
        - /bin/sh
        - -c
        - "until etcdctl --ca-file=/run/secrets/kubernetes.io/serviceaccount/ca.crt
        --endpoints=https://etcd.default.svc.cluster.local:2379 cluster-health;
        do echo '---'; sleep 2; done"
      restartPolicy: Never
      terminationGracePeriodSeconds: 1
      serviceAccount: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: default
  annotations:
  labels:
    app: etcd
spec:
  selector:
    app: etcd
  ports:
  - name: etcd
    port: 2379
    protocol: TCP

